### ISSUE TITLE
It always shows the indentation only lines

### ISSUE THREAD

**Issue by Neui** [wpillar/atom-trailing-spaces#18]
Regardless of the settings, it always shows the indentation on indentation-only-lines and it gets annoying.

Atom 0.209.0 
trailing-spaces 0.3.2 
Windows 7 <sup><sub>(HE 64-Bits)</sub></sup>

Example:
![Example](http://puu.sh/ipLO3/9e5066c0b6.png)

**Comment by kankaristo** [comment]
That's strange, it's working well for me:
![screenshot from 2015-06-15 19 26 29](https://cloud.githubusercontent.com/assets/3522333/8164856/88b53de6-1394-11e5-8da1-bf91a008eeec.png)

Do you have anything in your `styles.less` that could be overriding this?

**Comment by Neui** [comment]
Hm no, i only tried to overwrite `@comment` <sup><sub>(because the theme i am using got too tansparent comments)</sub></sup> 
There is my `styles.less` file if you want it:
![My styles.less file](http://puu.sh/ipR2o/ffea02779c.png)
I already tried commenting it out and reloading the window, but no difference. I even tried other themes (including the default Atom ones) but still, no difference.

**Comment by Neui** [comment]
Yesterday <sub><sup>(GMT+0100)</sup></sub> i noticed that this problem doesn't exist anymore... 
Well i checked today and Atom got updated to 0.210.0. I think it has been solved. I will tell here again if i expirence it again.

**Comment by kankaristo** [comment]
Closing the issue, please report back if it happens again. :)
