### ISSUE TITLE
Don't highlight "trailing" spaces on wrapped lines

### ISSUE THREAD

**Issue by afeld** [wpillar/atom-trailing-spaces#2]
![screen shot 2014-03-19 at 10 17 26 pm](https://f.cloud.github.com/assets/86842/2468339/d651383a-afd5-11e3-9dc0-39ccd528d9c7.png)

Also, thanks for the plugin!

**Comment by kankaristo** [comment]
@afeld, I'm not able to reproduce this anymore. This might have been a bug in Atom.

This package is almost entirely Less/CSS, so it just styles what Atom marks as trailing whitespace.

Does this issue still exist?

**Comment by afeld** [comment]
Looks fine now, thanks!
