### ISSUE TITLE
doesn't work for atom-1.4.1

### ISSUE THREAD

**Issue by Jayce** [wpillar/atom-trailing-spaces#20]
Setting:

![image](https://cloud.githubusercontent.com/assets/2687963/12635198/c8193e7c-c5bb-11e5-9614-cb405b5218eb.png)

![image](https://cloud.githubusercontent.com/assets/2687963/12635223/03800eb4-c5bc-11e5-86c6-87a658e09db7.png)

**Comment by kankaristo** [comment]
That's strange, it's working for me in Atom 1.5.0-beta1:
![screenshot from 2016-01-28 14-59-12](https://cloud.githubusercontent.com/assets/3522333/12645036/c943ba7a-c5cf-11e5-8da7-3c157a21bae7.png)

Could you open Atom's dev-tools (`Ctrl-Shift-I` or platform equivalent) and check if the indentation has the `.trailing-spaces` class? (click on the magnifying glass icon and then click on the indentation)

You seem to be modifying the `.indent-guide` class in your style sheet. The user's style sheet always overrides any package style sheets, so could your style sheet have something that breaks the highlight?

**Comment by Jayce** [comment]
It works! upgrade to `1.5.0`.

thank you!

**Comment by kankaristo** [comment]
Alright, I'm glad it started working! :smiley:
