### ISSUE TITLE
Don't highlight trailing spaces on current line while typing

### ISSUE THREAD

**Issue by davidhesselbom** [wpillar/atom-trailing-spaces#6]
Or at least allow users to choose not to. Having the trailing space I just typed light up, while I'm typing, is distracting.

**Comment by kankaristo** [comment]
This should be at least partially fixed in https://github.com/wpillar/atom-trailing-spaces/pull/15.

**Comment by kankaristo** [comment]
This is now partially fixed in v0.3.0.

It doesn't hide the highlight *while typing*, it just hides it on any line with a cursor (config option to enable/disable this).

@davidhesselbom, do you think this is an adequate fix?

**Comment by davidhesselbom** [comment]
I updated to 0.3.0 and restarted Atom, but I'm not seeing any highlighting at all, on any line, current, not current, trailing spaces or not. Maybe there's some broken configuration somewhere, but I don't understand how to change the configuration for this plugin?

**Comment by kankaristo** [comment]
Have you tried changing the config settings in Settings > Packages > trailing-spaces?

By default it doesn't highlight trailing whitespace for lines which contain a cursor or for lines where the whitespace is part of the indentation (i.e. lines containing only whitespace).

Toggling both of the config options on returns the package to its old behavior. I was hoping to make the effect more subtle, only catching your attention when necessary.

Apart from the config options, this package is nothing but Less style sheets. Checking which column the cursor is on becomes much more complex than that. We'd have to loop over (multiple) cursors every time the buffer changes, which might slow down the editor.

Personally, I prefer having the highlight off for the current line, even if I'm not at the line's end, so I'm not sure it's worth the effort. I'll accept a pull request, if someone figures out a lightweight way to do this. :)

**Comment by davidhesselbom** [comment]
So, it turns out that despite frequent (weekly?) 80MB updates for Atom from the software updater, I was still running version 0.130.0. Now that I've updated to a more recent version, I can see the configuration options and the plugin seems to work fine. 

If checking which column the cursor is on isn't feasible for performance reasons, then this will have to do. Like I said, it's an improvement! :)
