### ISSUE TITLE
Not working in atom 0.172.0

### ISSUE THREAD

**Issue by xdumaine** [wpillar/atom-trailing-spaces#9]
The package doesn't seem to have any effect in latest update. I'm not getting any errors, it just doesn't show any spaces highlighted. Restarted atom, uninstalled and re-installed the package, with no effect.

**Comment by wpillar** [comment]
What version of the package are you using

**Comment by pauldowman** [comment]
Same here. Version 0.2.3 and Atom 0.173.0.

**Comment by xdumaine** [comment]
Yep 0.2.3 and Atom 0.173.0

**Comment by wpillar** [comment]
I *think* I've just managed to publish v0.2.4 which should fix this issue. Please update and let me know!

**Comment by Unfocused** [comment]
Confirming, 0.2.4 seems to be working in Atom 0.174.0.

**Comment by xdumaine** [comment]
:+1: Working in 0.2.4 in Atom 0.174.0

**Comment by pauldowman** [comment]
:+1:
